<? php
echo '<!DOCTYPE html>';
echo '<html lang="zxx" class="no-js">';
echo '<head>';
echo '<!-- Mobile Specific Meta -->';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<!-- Favicon-->';
echo '<link rel="shortcut icon" href="img/logo_top_left.png">';
echo '<!-- Author Meta -->';
echo '<meta name="author" content="codepixer">';
echo '<!-- Meta Description -->';
echo '<meta name="description" content="">';
echo '<!-- Meta Keyword -->';
echo '<meta name="keywords" content="">';
echo '<!-- meta character set -->';
echo '<meta charset="UTF-8">';
echo '<!-- Site Title -->';
echo '<title>KIITFEST 5.0</title>';
echo '';
echo '<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">';
echo '<!--';
echo 'CSS';
echo '============================================= -->';
echo '<link rel="stylesheet" href="css/linearicons.css">';
echo '<link rel="stylesheet" href="css/font-awesome.min.css">';
echo '<link rel="stylesheet" href="css/bootstrap.css">';
echo '<link rel="stylesheet" href="css/magnific-popup.css">';
echo '<link rel="stylesheet" href="css/nice-select.css">';
echo '<link rel="stylesheet" href="css/animate.min.css">';
echo '<link rel="stylesheet" href="css/owl.carousel.css">';
echo '<link rel="stylesheet" href="css/main.css">';
echo '</head>';
echo '<body>';
echo '';
echo '<header id="header" id="home">';
echo '<div class="container">';
echo '<div class="row align-items-center justify-content-between d-flex">';
echo '<div id="logo">';
echo '<a href="index.html"><img src="img/logo_top_left.png" alt="" title="" style="height: 80px" /></a>';
echo '</div>';
echo '<nav id="nav-menu-container">';
echo '<ul class="nav-menu">';
echo '<li class="menu-active"><a href="#home">Home</a></li>';
echo '<li><a href="#videos">Gallery</a></li>';
echo '<!--li><a href="#speakers">Speakers</a></li-->';
echo '<!--li><a href="#schedule">Schedule</a></li-->';
echo '<li class="menu-has-children"><a href="">Events</a>';
echo '<ul>';
echo '<li><a href="https://kiitfest.org/technical.php">Technical</a></li>';
echo '<li><a href="https://kiitfest.org/cultural.php">Cultural</a></li>';
echo '<li><a href="https://kiitfest.org/quizfest.php">Quiz</a></li>';
echo '</ul>';
echo '</li>';
echo '<li><a class="ticker-btn" href="https://kiitfest.org/login.php">Login</a></li>';
echo '<li><a class="ticker-btn" href="https://kiitfest.org/signup.php">Register</a></li>';
echo '</ul>';
echo '</nav><!-- #nav-menu-container -->';
echo '</div>';
echo '</div>';
echo '</header><!-- #header -->';
echo '';
echo '';
echo '<!-- start banner Area -->';
echo '<section class="banner-area relative" id="home">';
echo '<div class="overlay overlay-bg"></div>';
echo '<div class="container">';
echo '<div class="row fullscreen d-flex align-items-center justify-content-center">';
echo '<div class="banner-content col-lg-9 col-md-12 col-sm-12">';
echo '<!--h6>And the wait is over</h6-->';
echo '<!--h1 class="text-white">';
echo 'KIIT FEST 5.0';
echo '</h1-->';
echo '<img src="img/logo.png" style="height: 180px" width="400px">';
echo '<div class="countdown">';
echo '<div id="timer" class="text-white"></div>';
echo '</div>';
echo '<h4><span class="lnr lnr-calendar-full"></span>  15th - 17th February, 2019</h4>';
echo '<!--h4><span class="lnr lnr-map"></span>  56/8, Dhanmondi, Dhaka - 1205</h4-->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- End banner Area -->';
echo '';
echo '<!-- Start home-video Area -->';
echo '<section class="home-video-area">';
echo '<div class="container-fluid">';
echo '<div class="row justify-content-end align-items-center">';
echo '<div class="col-lg-5 no-padding about-right col-sm-6 about_text">';
echo '<!--p class="top-title">Tutorial for beginner</p-->';
echo '<h1>About KIIT</h1>';
echo '<!--p><span>We are here to listen from you deliver exellence</span></p-->';
echo '<p align=justify>';
echo 'Established as a modest institute in the idyllic city of Bhubaneswar in June 1992, Kalinga Institute of Industrial Technology is now a profound institute for learning with a vision, to build an imperishable society through education which revolves around boundless learning, research and development. With our motto, “Knowledge is that which liberates”, it is a multidisciplinary varsity with an avant-garde infrastructure, comprising of twenty-three lush green world class campuses with academic wings, amphitheaters, auditoriums, conference rooms and smart class rooms. Having been granted the status of Deemed To Be University by the Ministry of HRD, Govt. of India in 2004, KIIT has been accorded the accreditation of the ‘A’ grade, by NAAC of UGC. KIIT offers more than 100 academic programs ranging from engineering to management, law to film studies. With 1800 faculties, 27000 students and 25 sq.km academic township, KIIT lets its students to explore new dimensions, enrich themselves and experience the best. Inculcating global prospective, KIIT stands 8th among the reputed private universities in India, proclaimed as an ‘A’ category, by the Ministry of HRD, Govt. of India, accredited by IET, UK as well as the ‘Tier-1’ accreditation (Washington Accord) for all engineering streams by the NBA, and is also a younger member of Association of Commonwealth Universities. KIIT is committed to high quality research and provides a supportive environment for the students along with a broad scope of programs starting from kindergarten to post graduation.';
echo '</p>';
echo '</div>';
echo '<section class="video-area col-lg-5 no-padding  kiit_logo">';
echo '<div class="overlay overlay-bg"></div>';
echo '<div class="containers">';
echo '<div class="video-content">';
echo '<center> <img class="img-fluid" src="https://kiitmun.org/wp-content/uploads/2018/05/kiit.png" alt=""> </center>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- End home-aboutus Area -->';
echo '';
echo '';
echo '';
echo '<!-- Start home-video Area -->';
echo '<section class="home-video-area">';
echo '<div class="container-fluid">';
echo '<div class="row justify-content-end align-items-center">';
echo '';
echo '<section class="video-area col-lg-5 no-padding">';
echo '<div class="overlay overlay-bg"></div>';
echo '<div class="containers">';
echo '<div class="video-content">';
echo '<center> <img class="img-fluid" src="https://kiitmun.org/wp-content/uploads/2018/05/kiss.png" alt=""> </center>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<div class="col-lg-1"></div>';
echo '<div class="col-lg-5 no-padding about-right">';
echo '<!--p class="top-title">Tutorial for beginner</p-->';
echo '<h1>About KISS</h1>';
echo '<!--p><span>We are here to listen from you deliver exellence</span></p-->';
echo '<p align=justify>';
echo 'Kalinga Institute of Social Sciences, the first tribal Deemed to Be University in India which started with 125 poor tribal children in 1993, in a rented house at Bhubaneswar. A sister concern of Kalinga Institute of Information Technology (KIIT), Kalinga Institute of Social Sciences (KISS) with more than 27,000 children and 62 indigenous tribes of Odisha, has been a home for over 37,000 students. KISS is a free of cost, fully residential educational institute, exclusively for penurious tribal children. These children are provided with free holistic education, skill development, career opportunities, food, accommodation, health care, and other basic necessities. With our Founder, Dr. Achyuta Samanta’s vision, KISS works to eradicate poverty, illiteracy and unemployment through quality education. It is a centre of learning for the underprivileged section of the society, with the philosophy of ‘Art Of Giving’. KISS has always nurtured a vision of a world which is free of hunger, poverty and illiteracy. UNESCO, UNICEF, UNFPA, as well as the US Federal Government have associated themselves with KISS for several initiatives and programs that have been undertaken by the institute. KISS aspires to work more and plans to open branches in all thirty districts of Odisha and also all the states of India. A branch of KISS, KISS-DELHI is successfully operating in NCR with the collaboration of Government Of Delhi.';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- End home-aboutus Area -->';
echo '';
echo '';
echo '';
echo '';
echo '<!-- Start video-sec Area -->';
echo '<section class="video-sec-area section-gap" id="videos">';
echo '<div class="container">';
echo '<div class="row justify-content-center align-items-center ">';
echo '<div class="col-lg-4 video-left col-sm-12">';
echo '<h6>Another platform to show your talent</h6>';
echo '<h1>Are you dreaming of KIITFEST? <br>';
echo 'that will change you</h1>';
echo '<!--p><span>We are here to listen from you deliver exellence</span></p>';
echo '<p>';
echo 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.';
echo '</p>';
echo '<a class="primary-btn" href="#">Get Started now</a-->';
echo '</div>';
echo '<div class="col-lg-8 videoWrapper" >';
echo '<!--div class="active-video-carusel">';
echo '<div class="item video-right justify-content-center align-items-center d-flex" style="background:url(img/video-bg.jpg) no-repeat center;background-size: cover;">';
echo '<div class="overlay overlay-bg"></div>';
echo '<a class="play-btn" href="https://www.youtube.com/watch?v=ARA0AxrnHdM"><img class="img-fluid" src="img/play-icon.png" alt=""></a>';
echo '</div>';
echo '<div class="item video-right justify-content-center align-items-center d-flex" style="background:url(img/video-bg.jpg) no-repeat center;background-size: cover;">';
echo '<div class="overlay overlay-bg"></div>';
echo '<a class="play-btn" href="https://www.youtube.com/watch?v=ARA0AxrnHdM"><img class="img-fluid" src="img/play-icon.png" alt=""></a>';
echo '</div>';
echo '<div class="item video-right justify-content-center align-items-center d-flex" style="background:url(img/video-bg.jpg) no-repeat center;background-size: cover;">';
echo '<div class="overlay overlay-bg"></div>';
echo '<a class="play-btn" href="https://www.youtube.com/watch?v=ARA0AxrnHdM"><img class="img-fluid" src="img/play-icon.png" alt=""></a>';
echo '</div>';
echo '</div-->';
echo '<iframe width="100%" height="auto" src="https://www.youtube-nocookie.com/embed/Op7SHPDHwdI?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<hr>';
echo '</section>';
echo '<!-- End video-sec Area -->';
echo '';
echo '';
echo '<br>';
echo '<div class="container-fluid">';
echo '<center> <h3 style="font-family:georgia"> Some Moments from Past KIITFESTS </h3> </center>';
echo '</div>';
echo '<br>';
echo '';
echo '';
echo '';
echo '<!-- Start home-aboutus Area -->';
echo '<section class="home-aboutus-area1">';
echo '<div class="container-fluid">';
echo '<div class="row align-items-center">';
echo '<div class="col-lg-4 no-padding about-left videoWrapper">';
echo '<iframe width="100%" height="auto" src="https://www.youtube.com/embed/5ePlvE-jDzo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '<div class="col-lg-4 no-padding about-left videoWrapper">';
echo '<iframe width="100%" height="auto" src="https://www.youtube.com/embed/0gmgAcypwOc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '<div class="col-lg-4 no-padding about-left videoWrapper">';
echo '<iframe width="100%" height="auto" src="https://www.youtube.com/embed/HxYfyi1YSRE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- End home-aboutus Area -->';
echo '';
echo '<br>';
echo '';
echo '<!--start labelling-->';
echo '<!--div class="container-fluid">';
echo '<div class="row align-items-center">';
echo '<div class="col-lg-4 no-padding about-left">';
echo '<center> <h3 > Ankit Tiwari in KIITFEST 3.0 </h2> </center>';
echo '</div>';
echo '<div class="col-lg-4 no-padding about-left">';
echo '<center> <h3 > Sonu Nigam in KIITFEST 4.0 </h2> </center>';
echo '</div>';
echo '<div class="col-lg-4 no-padding about-left">';
echo '<center> <h3 > KIITFEST 4.0 AFTER MOVIE </h2> </center>';
echo '</div>';
echo '</div>';
echo '</div-->';
echo '<!--end labelling-->';
echo '<hr>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<!-- Start spekers Area -->';
echo '<!--section class="spekers-area pb-100" id="speakers">';
echo '<div class="container-fluid">';
echo '<div class="row no-padding">';
echo '<div class="active-speaker-carusel col-lg-12 no-padding">';
echo '<div class="single-speaker item">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-6 speaker-img no-padding">';
echo '<img src="img/s1.jpg" alt="">';
echo '</div>';
echo '<div class="col-md-6 speaker-info no-padding">';
echo '<h6 class="text-uppercase">speaker 01</h6>';
echo '<h1 class="text-white">Essie Ballard</h1>';
echo '<p>';
echo 'Computer users and programmers have become so accustomed to using Windows, even for the changing capabilities and the appearances.';
echo '</p>';
echo '<p><span class="lnr lnr-phone-handset"></span>+880 (012) 8954 253</p>';
echo '<p><span class="lnr lnr-location"></span>iamspeaker@gmail.com</p>';
echo '<ul>';
echo '<a href="#"><i class="fa fa-facebook"></i></a>';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '<a href="#"><i class="fa fa-dribbble"></i></a>';
echo '<a href="#"><i class="fa fa-behance"></i></a>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="single-speaker item">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-6 speaker-img no-padding">';
echo '<img src="img/s2.jpg" alt="">';
echo '</div>';
echo '<div class="col-md-6 speaker-info no-padding">';
echo '<h6 class="text-uppercase">speaker 02</h6>';
echo '<h1 class="text-white">Elizabeth Stokes</h1>';
echo '<p>';
echo 'Computer users and programmers have become so accustomed to using Windows, even for the changing capabilities and the appearances.';
echo '</p>';
echo '<p><span class="lnr lnr-phone-handset"></span>+880 (012) 8954 253</p>';
echo '<p><span class="lnr lnr-location"></span>iamspeaker@gmail.com</p>';
echo '<ul>';
echo '<a href="#"><i class="fa fa-facebook"></i></a>';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '<a href="#"><i class="fa fa-dribbble"></i></a>';
echo '<a href="#"><i class="fa fa-behance"></i></a>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="single-speaker item">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-6 speaker-img no-padding">';
echo '<img src="img/s1.jpg" alt="">';
echo '</div>';
echo '<div class="col-md-6 speaker-info no-padding">';
echo '<h6 class="text-uppercase">speaker 01</h6>';
echo '<h1 class="text-white">Essie Ballard</h1>';
echo '<p>';
echo 'Computer users and programmers have become so accustomed to using Windows, even for the changing capabilities and the appearances.';
echo '</p>';
echo '<p><span class="lnr lnr-phone-handset"></span>+880 (012) 8954 253</p>';
echo '<p><span class="lnr lnr-location"></span>iamspeaker@gmail.com</p>';
echo '<ul>';
echo '<a href="#"><i class="fa fa-facebook"></i></a>';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '<a href="#"><i class="fa fa-dribbble"></i></a>';
echo '<a href="#"><i class="fa fa-behance"></i></a>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="single-speaker item">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-6 speaker-img no-padding">';
echo '<img src="img/s2.jpg" alt="">';
echo '</div>';
echo '<div class="col-md-6 speaker-info no-padding">';
echo '<h6 class="text-uppercase">speaker 02</h6>';
echo '<h1 class="text-white">Elizabeth Stokes</h1>';
echo '<p>';
echo 'Computer users and programmers have become so accustomed to using Windows, even for the changing capabilities and the appearances.';
echo '</p>';
echo '<p><span class="lnr lnr-phone-handset"></span>+880 (012) 8954 253</p>';
echo '<p><span class="lnr lnr-location"></span>iamspeaker@gmail.com</p>';
echo '<ul>';
echo '<a href="#"><i class="fa fa-facebook"></i></a>';
echo '<a href="#"><i class="fa fa-twitter"></i></a>';
echo '<a href="#"><i class="fa fa-dribbble"></i></a>';
echo '<a href="#"><i class="fa fa-behance"></i></a>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section-->';
echo '<!-- End spekers Area -->';
echo '';
echo '';
echo '<!-- Start schedule Area -->';
echo '<!--section class="schedule-area pb-100" id="schedule">';
echo '<div class="container">';
echo '<div class="row d-flex justify-content-center">';
echo '<div class="menu-content pb-70 col-lg-8">';
echo '<div class="title text-center">';
echo '<h1 class="mb-10">How Our Customers Treat Us</h1>';
echo '<p>Who are in extremely love with eco friendly system.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="table-wrap col-lg-12">';
echo '<table class="schdule-table table table-bordered">';
echo '<thead class="thead-light">';
echo '<tr>';
echo '<th class="head" scope="col">sl</th>';
echo '<th class="head" scope="col">session</th>';
echo '<th class="head" scope="col">speaker</th>';
echo '<th class="head" scope="col">vanue</th>';
echo '<th class="head" scope="col">time</th>';
echo '</tr>';
echo '</thead>';
echo '<tbody>';
echo '<tr>';
echo '<th class="name" scope="row">01</th>';
echo '<td>Reception & Taling Seats</td>';
echo '<td>Isabelle Cooper</td>';
echo '<td>3rd Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '<tr>';
echo '<th class="name" scope="row">02</th>';
echo '<td>Breakfast and rest</td>';
echo '<td>N/A</td>';
echo '<td>4th Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '<tr>';
echo '<th class="name" scope="row">03</th>';
echo '<td>Reception & Taling Seats</td>';
echo '<td>Jane Daniel</td>';
echo '<td>2nd Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '<tr>';
echo '<th class="name" scope="row">04</th>';
echo '<td>Next generation speech</td>';
echo '<td>Billy Barton</td>';
echo '<td>1st Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '<tr>';
echo '<th class="name" scope="row">05</th>';
echo '<td>Sppech for young people</td>';
echo '<td>Flora Gonzales</td>';
echo '<td>4rd Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '<tr>';
echo '<th class="name" scope="row">06</th>';
echo '<td>Lunch Break</td>';
echo '<td>N/A</td>';
echo '<td>3rd Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '<tr>';
echo '<th class="name" scope="row">07</th>';
echo '<td>Sppech for Middle aged people</td>';
echo '<td>Francisco Barrett</td>';
echo '<td>1st Hall Room</td>';
echo '<td>02.00</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section-->';
echo '<!-- End schedule Area -->';
echo '';
echo '<!-- Start price Area -->';
echo '<section class="price-area section-gap">';
echo '<div class="container">';
echo '<div class="row d-flex justify-content-center">';
echo '<div class="menu-content pb-70 col-lg-8">';
echo '<div class="title text-center">';
echo '<h1 class="mb-10">Events</h1>';
echo '<p>Events to Showcase your talents</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-lg-4 col-md-6 single-price">';
echo '<div class="top-part">';
echo '<h1 class="package-no">01</h1>';
echo '<h4>Technical</h4>';
echo '<p>For the Tech savvies</p>';
echo '</div>';
echo '<div class="package-list">';
echo '<ul>';
echo '<li>ELECTTRIFYN</li>';
echo '<li>KINESIS</li>';
echo '<li>KSOM</li>';
echo '<li>LUMINARE</li>';
echo '<li>MIRABILIA</li>';
echo '<li>NIRMINITE</li>';
echo '<li>VIDNAN</li>';
echo '<li>YANTRIKI</li>';
echo '</ul>';
echo '</div>';
echo '<!--div class="bottom-part">';
echo '<h1>£199.00</h1>';
echo '<a class="price-btn text-uppercase" href="#">Buy Now</a>';
echo '</div-->';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 single-price">';
echo '<div class="top-part">';
echo '<h1 class="package-no">02</h1>';
echo '<h4>Cultural</h4>';
echo '<p>For the individuals</p>';
echo '</div>';
echo '<div class="package-list">';
echo '<ul>';
echo '<li>FROZEN IN TIME</li>';
echo '<li>MISMATCH - The Masterchef Event</li>';
echo '<li>Open Sesame</li>';
echo '<li>Zara Nachke Dikha</li>';
echo '<li>Tell A Tale</li>';
echo '<li>KALAKAAR</li>';
echo '<li>Isle To Glory</li>';
echo '<li>Instant-o-fie</li>';
echo '<li>FUEGO</li>';
echo '<li>CHITRA-VI-CHITRA-CHITRAM</li>';
echo '<li>Alankaar</li>';
echo '<li>Illustory</li>';
echo '</ul>';
echo '</div>';
echo '<!--div class="bottom-part">';
echo '<h1>£199.00</h1>';
echo '<a class="price-btn text-uppercase" href="#">Buy Now</a>';
echo '</div-->';
echo '</div>';
echo '<div class="col-lg-4 col-md-6 single-price">';
echo '<div class="top-part">';
echo '<h1 class="package-no">03</h1>';
echo '<h4>Quiz</h4>';
echo '<p>For the individuals</p>';
echo '</div>';
echo '<div class="package-list">';
echo '<ul>';
echo '<li>Udghosh</li>';
echo '<li>Biz-tech Quiz</li>';
echo '<li>FLAMES Quiz</li>';
echo '<li>Travel,Living,Culture</li>';
echo '</ul>';
echo '</div>';
echo '<!--div class="bottom-part">';
echo '<h1>£199.00</h1>';
echo '<a class="price-btn text-uppercase" href="#">Buy Now</a>';
echo '</div-->';
echo '</div>';
echo '<!--div class="col-lg-3 col-md-6 single-price">';
echo '<div class="top-part">';
echo '<h1 class="package-no">04</h1>';
echo '<h4>Exclusive</h4>';
echo '<p>For the individuals</p>';
echo '</div>';
echo '<div class="package-list">';
echo '<ul>';
echo '<li>Secure Online Transfer</li>';
echo '<li>Unlimited Styles for interface</li>';
echo '<li>Reliable Customer Service</li>';
echo '</ul>';
echo '</div>';
echo '<div class="bottom-part">';
echo '<h1>£199.00</h1>';
echo '<a class="price-btn text-uppercase" href="#">Buy Now</a>';
echo '</div>';
echo '</div>';
echo '</div-->';
echo '</div>';
echo '</section>';
echo '<!-- End price Area -->';
echo '';
echo '<!-- Start brand Area -->';
echo '<section class="brand-area section-gap">';
echo '<div class="container">';
echo '<div class="row logo-wrap">';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/audi_logo.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/hero.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/ccd.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/nikon.png" alt="" style="width:80px">';
echo '</a>';
echo '';
echo '</div>';
echo '<br><br>';
echo '<div class="row logo-wrap">';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/hp.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/dell.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<br>';
echo '<img class="d-block mx-auto" src="img/bigfm.jpg" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<br>';
echo '<img class="d-block mx-auto" src="img/mindfire.png" alt="" style="width:80px">';
echo '</a>';
echo '';
echo '</div>';
echo '<br><br>';
echo '<div class="row logo-wrap">';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/byju.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<br>';
echo '<img class="d-block mx-auto" src="img/samsung.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<br><br>';
echo '<img class="d-block mx-auto" src="img/icici.png" alt="" style="width:150px">';
echo '</a>';
echo '<a class="col single-img" href="#">';
echo '<img class="d-block mx-auto" src="img/aircel.png" alt="" style="width:80px">';
echo '</a>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '</section>';
echo '<!-- End brand Area -->';
echo '';
echo '';
echo '<!-- Start callaction Area -->';
echo '<!--section class="callaction-area relative section-gap">';
echo '<div class="overlay overlay-bg"></div>';
echo '<div class="container">';
echo '<div class="row justify-content-center">';
echo '<div class="col-lg-10">';
echo '<h1 class="text-white">Huge Transaction in last Week</h1>';
echo '<p>';
echo 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore  et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.';
echo '</p>';
echo '<a class="callaction-btn" href="#">Become a Member</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</section-->';
echo '<!-- End callaction Area -->';
echo '';
echo '';
echo '<!-- start footer Area -->';
echo '<footer class="footer-area section-gap">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-5 col-md-6 col-sm-6">';
echo '<div class="single-footer-widget">';
echo '<h2 style="color: white"> Contact Us :  </h2>';
echo '<br>';
echo '<p>';
echo 'email : info@kiitfest.org</p>';
echo '<p>KIIT UNIVERSITY,<br>';
echo 'Patia, <br>';
echo 'Bhubaneswar - 751024</p>';
echo '<!--h6>About Us</h6-->';
echo '<!--p>';
echo 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.';
echo '</p>';
echo '<p class="footer-text"-->';
echo '<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-5  col-md-6 col-sm-6">';
echo '<!--div class="single-footer-widget">';
echo '<h6>Newsletter</h6>';
echo '<p>Stay update with us</p>';
echo '<div class="" id="mc_embed_signup">';
echo '<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">';
echo '<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">';
echo '<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>';
echo '<div style="position: absolute; left: -5000px;">';
echo '<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">';
echo '</div>';
echo '';
echo '<div class="info"></div>';
echo '</form>';
echo '</div>';
echo '</div-->';
echo '</div>';
echo '<div class="col-lg-2 col-md-6 col-sm-6 social-widget">';
echo '<div class="single-footer-widget">';
echo '<h6>Follow Us</h6>';
echo '<p>Let us be social</p>';
echo '<div class="footer-social d-flex align-items-center">';
echo '<a href="https://facebook.com/kiitfest"><i class="fa fa-facebook"></i></a>';
echo '<a href="https://twitter.com/kiitfest"><i class="fa fa-twitter"></i></a>';
echo '<a href="https://instagram.com/kiitfest"><i class="fa fa-instagram"></i></a>';
echo '<!--a href="#"><i class="fa fa-behance"></i></a-->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!-- End footer Area -->';
echo '';
echo '<script src="js/vendor/jquery-2.2.4.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>';
echo '<script src="js/vendor/bootstrap.min.js"></script>';
echo '<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>';
echo '<script src="js/easing.min.js"></script>';
echo '<script src="js/hoverIntent.js"></script>';
echo '<script src="js/superfish.min.js"></script>';
echo '<script src="js/jquery.ajaxchimp.min.js"></script>';
echo '<script src="js/jquery.magnific-popup.min.js"></script>';
echo '<script src="js/owl.carousel.min.js"></script>';
echo '<script src="js/jquery.sticky.js"></script>';
echo '<script src="js/jquery.nice-select.min.js"></script>';
echo '<script src="js/parallax.min.js"></script>';
echo '<script src="js/mail-script.js"></script>';
echo '<script src="js/main.js"></script>';
echo '</body>';
echo '</html>';
echo '';
echo '';
echo '<style type="text/css">';
echo '';
echo '.videoWrapper {';
echo 'position: relative;';
echo 'padding-bottom: 40.25%; /* 16:9 */';
echo 'padding-top: 5px;';
echo 'height: 0;';
echo '}';
echo '.videoWrapper iframe {';
echo 'position: absolute;';
echo 'top: 0;';
echo 'left: 0;';
echo 'width: 100%;';
echo 'height: 100%;';
echo '}';
echo '';
echo '';
echo '@media screen and (max-width: 931px) {';
echo '.container-fluid { display: flex; flex-flow: column; }';
echo '.kiit_logo{ order: 1; }';
echo '.about_text { order: 2;  }';
echo '}';
echo '';
echo '';
echo '';
echo '</style>';
echo '';
echo '';
echo '';
?>
